### ISSUE TITLE
Language changing not complete

### ISSUE THREAD

**Issue by Tsunghao-C** [Tsunghao-C/ft_Transcendence#52]
Several details of lauguage switch need to be handled:
1. The button `Back to Login` in the registration page
2. The home page display
3. The tab names in the drop-down menu
4. And the content inside each tabs

![Screenshot from 2024-12-11 11-41-55](https://github.com/user-attachments/assets/8d8af471-cf95-46a2-8d22-3b15a757208d)

**Comment by asut00** [comment]
i can check these

**Comment by Tsunghao-C** [comment]
Closed by #77
