### ISSUE TITLE
Friend online/offline status is not updated

### ISSUE THREAD

**Issue by Tsunghao-C** [Tsunghao-C/ft_Transcendence#73]
I found that when you add a friend user and click into the profile of that user, the status will always be "online" even though the friend user is logged out.

![Screenshot from 2024-12-18 12-07-03](https://github.com/user-attachments/assets/f4aa51df-685f-4c9f-9415-b57ebf1da503)

**Comment by Atwazar** [comment]
Updated with cron every 15 minutes, we need to think about making it shorter for release
