### ISSUE TITLE
Several pop out window or button won't remove automatically

### ISSUE THREAD

**Issue by Tsunghao-C** [Tsunghao-C/ft_Transcendence#94]
When you click "Join a room" in the online multiplayer mode, the pop out window will always be there even after you decided to navigate to some other pages.

Same as the player ready button and waiting for player message block. Need to clean them out when they are no longer relevant. Currently you need to manually refresh the webpage to get rid of idling buttons or windows.
![Screenshot 2024-12-26 at 12 55 38](https://github.com/user-attachments/assets/a0997529-a7f8-4dde-a88c-68c6b2d4b88b)

**Comment by Atwazar** [comment]
Issue is closed in some PR
